### ISSUE TITLE
Get video frame rate

### ISSUE THREAD

**Issue by andresenwc** [gcanat/video_reader-rs#12]
I don't see a way to get video frame rate (which could be useful to compute a sampling rate). Could something like this be added (or have I overlooked this functionality)?

**Comment by gcanat** [comment]
You are correct. I can look into adding this. Should be easy.

**Comment by gcanat** [comment]
You can try if you pull latest master and build from there using `maturin develop -r`
then you can do:
```python
import video_reader as vr
info_dict = vr.get_info("/path/to/video.mp4")
print(info_dict["fps"])
```
