### ISSUE TITLE
add support to mp4 file get_batch with audio data. 

### ISSUE THREAD

**Issue by wangdaw2023** [gcanat/video_reader-rs#17]
Thanks for your great job. I tried this library with some mp4 files with get_batch method to decode specific video frames. This mp4 files have both video and audio data in it. However it outputs all black images (should be all zero data).  I suspect the library can not support this kind of mp4  files with both video and audio data. Would we support this scenario in plan?

**Comment by gcanat** [comment]
Indeed I can reproduce the issue. So I will try to look into it.
Meanwhile, maybe you can workaround it by using `video_reader.decode()` if you are taking sub-clip of a video with evenly spaced frames you can use for example `video_reader.decode("/path/to/file.mp4", compression_factor=0.25, start_frame=100, end_frame=200)`. Which would take 1 frame out of 4 (compression_factor=0.25) between frame 100 and 200.

**Comment by gcanat** [comment]
Should be fixed in ac35dadc511f73eed3ec48a1b1b9699f3ac0ddd6
