### ISSUE TITLE
[Feature Request] - Return a Torch Numpy Array of shape (N, H, W, C).

### ISSUE THREAD

**Issue by NevermindNilas** [gcanat/video_reader-rs#2]
The title is relatively self explanatory,

On video / frame read give the user the option through either a str or bool variable to decide what they would prefer to be returned, a numpy array or torch tensor array.

Most ML / AI related subject work on some level with pytorch and avoiding an unnecessary conversion from numpy uint8 -> torch uint8 would save some performance overhead even if generally not by a huge margin. 

Pytorch already provides a nice little function for that `torch.frombuffer` that should simplify things at least on the pythonic frontend, not sure how this would work for rust.

**Comment by gcanat** [comment]
You can do `tch_frames = torch.from_numpy(np_frames)`. It is really inexpensive operation as the numpy array and torch tensor will share the same memory location.

https://pytorch.org/docs/stable/generated/torch.from_numpy.html
https://discuss.pytorch.org/t/what-is-the-overhead-of-transforming-numpy-to-torch-and-vice-versa/7395

**Comment by NevermindNilas** [comment]
Hmm, I ended up doing some tests on my side and both you and the documentation provided were right, the performance penalty is virtually negligible.

I guess I must have remembered wrong.
