### ISSUE TITLE
[Feature Ruquest] - Resize function should work for both downscaling and upscaling.

### ISSUE THREAD

**Issue by NevermindNilas** [gcanat/video_reader-rs#3]
```resize: optional resizing for the video. If the value is bigger than the actual video size, no resizing will be done```

The resize should imho work both ways in order to accommodate a larger use case, otherwise resize is a ambiguous terminology and maybe should be replaced by downscale?

**Comment by gcanat** [comment]
Sounds reasonable. I will look into it :+1:

**Comment by NevermindNilas** [comment]
Sounds good can't wait for the pip wheel.

**Comment by gcanat** [comment]
Should be done in #8 
Also you an now install with `pip install video-reader-rs` :v:
