### ISSUE TITLE
[BUG] - Can't compile using maturin on Arch Linux

### ISSUE THREAD

**Issue by NevermindNilas** [gcanat/video_reader-rs#4]
Hi,

When trying to compile I get the following error:
[error.txt](https://github.com/user-attachments/files/16013834/error.txt)

Using Arch
Python 3.11.8 inside a VENV
Made sure everything is up to date with the latest versions.
```
error[E0560]: struct `Config` has no field named `safe`
   --> src/video_io.rs:180:13
    |
180 |             safe: true,
    |             ^^^^ `Config` does not have this field
    |
    = note: all struct fields are already assigned

For more information about this error, try `rustc --explain E0560`.
error: could not compile `video_reader-rs` (lib) due to 1 previous error
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/home/nilas/Documents/video_reader-rs/venv/bin/python" PYTHON_SYS_EXECUTABLE="/home/nilas/Documents/video_reader-rs/venv/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/nilas/Documents/video_reader-rs/Cargo.toml" "--release" "--lib"
```

**Comment by NevermindNilas** [comment]
running the prompted `rustc --explain E0560`

I get the following: 
```
An unknown field was specified into a structure.

Erroneous code example:

struct Simba {
    mother: u32,
}

let s = Simba { mother: 1, father: 0 };
// error: structure `Simba` has no field named `father`

Verify you didn't misspell the field's name or that the field exists. Example:

struct Simba {
    mother: u32,
    father: u32,
}

let s = Simba { mother: 1, father: 0 }; // ok!
```

**Comment by gcanat** [comment]
Oh yes I know this error.  It's probably because you are using ffmpeg 6 (or 7) ?
If so, just comment out `safe: true` in `src/video_io.rs` line 180, like this `// safe: true`.

I will try to fix so it detects the ffmpeg version and disable this attribute if needed.

**Comment by NevermindNilas** [comment]
![image](https://github.com/gcanat/video_reader-rs/assets/128264457/24ffc9d5-9189-45bd-976c-7b23c582531e)

Apparently you were right about FFMPEG ( I never recall installing it lol )

![image](https://github.com/gcanat/video_reader-rs/assets/128264457/5a43172f-4442-45dc-a02e-6644cb531191)

After doing the proposed modifications everything seems to be fine, time to benchmark.

**Comment by gcanat** [comment]
If you pull latest changes you should be able to compile with
```bash
maturin develop --release --features ffmpeg_6_0
```

**Comment by Manamama** [comment]
Just quick note that some `ffmpeg-dev` type files are missing, despite a hand compiled ffmpeg even, too, and same error durimg regular: `pip install video-reader-rs -v`. 
Grok advised: 
```
export PKG_CONFIG_PATH=/data/data/com.termux/files/usr/opt/ffmpeg7/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/opt/ffmpeg7/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=/data/data/com.termux/files/usr/opt/ffmpeg7/include:$C_INCLUDE_PATH
export LIBRARY_PATH=/data/data/com.termux/files/usr/opt/ffmpeg7/lib:$LIBRARY_PATH
```
but that did not work. 

Will try your tip instead, by git cloning, but FYI.

**Comment by Manamama** [comment]
Fix: 
`sed -i 's/^[[:space:]]*safe: true,/\/\/ safe: true,/' src/reader.rs`

**Comment by FullstackJack** [comment]
Wouldn't it make more sense to require ffmpeg >= 6.0 by default? It complicates installation when video_reader-rs is used in other projects. I'd like to see about getting this package to replace `decord` in Wan2GP, but the extra `git clone <this repo> `  and `maturin develop --release --features ffmpeg_6_0`  would definitely not be well received.
