### ISSUE TITLE
[ Question / Feature Request ] - Is it possible to loop over a video for Super Resolution or other tasks

### ISSUE THREAD

**Issue by NevermindNilas** [gcanat/video_reader-rs#5]
Something like this instantly causes a mem overflow
```py
import video_reader
import cv2

from tqdm import tqdm

video = video_reader.decode("/home/nilas/Downloads/videoplayback.mp4")

for i in tqdm(range(video.shape[0])):
    frame = video[i]
    cv2.imshow("frame", frame)
    cv2.waitKey(1)
```

Which is understandable since basically all frames are stored inside one numpy array of some huge N dimension before any processing is done.

Problem arises when the workflow requires let's say a movie to be processed that may have hundreds of thousands of frames to be stored. This would innately make the decode function virtually useless since unless you went out of your way to download ram off of Google you won't be able to process this in a reliable manner that would work with most 

Having a `.read` or `.get_frame` function that simply returns a numpy array of shape [ 1, w, h, 3 ] would suffice.
Something like this in theory could work just fine:
```py
video = video.decode_loop("path_here")

num_frames = video.num_frames # assuming a function like this exists

for i in tqdm(range(num_frames)):
    frame = video.get_frame(i)

    # Do some processing here, like upscaling
    frame = cv2.resize(frame, (3840, 2160))
    cv2.imshow("frame", frame)
    cv2.waitKey(1)
```

This would be slightly harder but with subprocesses at least in python + ffmpeg pipes it can be done and it is relatively speedy ( 13700k, 1080p, ffmpeg 7 results are about 440fps +- for pure decode ).

**Comment by NevermindNilas** [comment]
![image](https://github.com/gcanat/video_reader-rs/assets/128264457/2386666d-80a3-4100-8a5d-abdc5381dc56)

Here are some of my internal tests on pure decode and decord at the very least topped all results nearly performing as well as simply using FFMPEG without any other extra tasks.

**Comment by gcanat** [comment]
Try this:
```python
import video_reader
import cv2

from tqdm import tqdm

videoname = "/home/nilas/Downloads/videoplayback.mp4"
video_shape = video_reader.get_shape(videoname)

for i in tqdm(range(video_shape[0])):
    frame = video_reader.get_batch(videoname, [i])
   # frame shape will be: (1, H, W, C) so we need to squeeze to remove the first dim
    cv2.imshow("frame", frame.squeeze())
    cv2.waitKey(1)
```

**Comment by NevermindNilas** [comment]
```bash
python test.py
  0%|                                                                                                                                                                                                                     | 0/3649 [00:00<?, ?it/s]thread '<unnamed>' panicked at src/video_io.rs:479:21:
No Reducer to get the frames
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  0%|                                                                                                                                                                                                                     | 0/3649 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/nilas/Downloads/test/test.py", line 10, in <module>
    frame = video_reader.get_batch(videoname, [i])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: No Reducer to get the frames
```

**Comment by gcanat** [comment]
works fine here, maybe you need to git pull again if you cloned the repo before last commits ?

**Comment by NevermindNilas** [comment]
![image](https://github.com/gcanat/video_reader-rs/assets/128264457/4817c713-8898-4405-8e21-0f51a0a90710)

All up to date on my side :thinking:

**Comment by gcanat** [comment]
Ok I see. It looks like video_reader is falling back to `get_batch_safe` because it did not like what was found in the metadata of the video. Can you share the video ?

**Comment by NevermindNilas** [comment]
It was a random video I got from youtube, can sure do.

Github gave me a flat NO so I uploaded it here, hopefully it doesn't alter the video metadata, otherwise I Can try to do it through discord.
https://gofile.io/d/dgiBAP

**Comment by gcanat** [comment]
So I've pushed some changes: the `get_batch` method no longer falls back to decoding without seeking unless you explicitly ask for it with `get_batch(filename, indices, with_fallback=True)`. Thus I removed the `get_batch_nofb` method as it is redundant.

Combing back to the previous example, you can do something like this to be a bit more efficient and get chunk of frames instead of frame by frame:
```python
import sys
from time import time

import cv2
import video_reader
from tqdm import tqdm

videoname = sys.argv[1]
chunk_size = int(sys.argv[2])

video_shape = video_reader.get_shape(videoname)
print("Video shape:", video_shape)

i = 0
start = time()
for i in tqdm(range(0, video_shape[0], chunk_size)):
    indices = list(range(i, min(i + chunk_size, video_shape[0])))
    frames = video_reader.get_batch(videoname, indices)
    for j in range(len(indices)):
        cv2.imshow("frame", frames[j])
        cv2.waitKey(1)
print(f"Done in {time() - start} seconds")
```

and then run it with `python script.py /path/to/your/video.map 200` if you want to have chunks of 200 frames. Memory consumption remains very low in my experience even with bigger chunk sizes.

**Comment by NevermindNilas** [comment]
after some small modifications for simplicity purposes
```py
import sys
import video_reader
from tqdm import tqdm

videoname = "/home/nilas/Downloads/videoplayback.mp4"
chunk_size = 500

video_shape = video_reader.get_shape(videoname)
print("Video shape:", video_shape)

for i in tqdm(range(0, video_shape[0], chunk_size)):
    indices = list(range(i, min(i + chunk_size, video_shape[0])))
    frames = video_reader.get_batch(videoname, indices)
```

I get the following it/s at 500 batch size:
```
100%|█████████████████████████████████████████████████████████████████████████████████| 8/8 [00:17<00:00,  2.16s/it]
```

So video_reader-rs got approximately 250 FPS using the script you've shared with very small modifications on my side ( I did test a 1000 batch size as well but saw no major differences )

Using the command:
```ffmpeg -i videoplayback.mp4 -f null -```

I get the following:
frame= 3649 fps=1475 q=-0.0 Lsize=N/A time=00:02:01.63 bitrate=N/A speed=49.2x  
( Of course this is just to know the theoretical maximum, it doesn't account for numpy and other conversions )

Benching with a similar setup and decord:
```py
import decord
from tqdm import tqdm

videoname = "/home/nilas/Downloads/videoplayback.mp4"
chunk_size = 500

vr = decord.VideoReader(videoname)
video_length = len(vr)
print("Video length:", video_length)

for i in tqdm(range(0, video_length, chunk_size)):
    end = min(i + chunk_size, video_length)
    frames = vr.get_batch(range(i, end)).asnumpy() # turning it into a numpy array for fairness
```
```
python test.py
Video length: 3649
100%|███████████████████████████████████████████████████████| 8/8 [00:07<00:00,  1.06it/s]
```

This should equate to roughly 500FPS which is still marginally lower than my theoretical maximum of 590-600 but it suffices for now.

Ofc I tested your memory claims as well and saw significantly better memory usage using video_reader-rs, I didn't go out of my way to log it but I can confirm that claim 100%.

**Comment by NevermindNilas** [comment]
I did a very quick test using FFMPEG + Subprocess:
```py
import numpy as np
import subprocess
import cv2
from tqdm import tqdm

video_name = "/home/nilas/Downloads/videoplayback.mp4"

ffmpeg_command = [
    'ffmpeg',
    '-i', video_name,
    '-f', 'image2pipe',
    '-pix_fmt', 'rgb24',
    '-vcodec', 'rawvideo',
    '-'
]

process = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, bufsize=10**8)
cap = cv2.VideoCapture(video_name)
total_frame_count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
cap.release()

frame_width = 1920
frame_height = 1080
bytes_per_frame = frame_width * frame_height * 3

for _ in tqdm(range(int(total_frame_count))):
    raw_frame = process.stdout.read(bytes_per_frame)
    if not raw_frame:
        break

    frame = np.frombuffer(raw_frame, dtype=np.uint8).reshape((frame_height, frame_width, 3))

process.stdout.close()
process.wait()
```

The reported performance seems to be:
```
python test.py
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3649/3649 [00:05<00:00, 640.02it/s]
```

Which is weird because I am only getting approximately 440FPS on Windows, weird...

**Comment by gcanat** [comment]
Thanks for the benchmark.
Indeed this use case is not exactly what I had in mind when developing video_reader. I think there's 2 differences here with decord:
- `video_reader.get_batch()` will instantiate the VideoReader struct (on the rust side) each time it is called so it will get all the metada from the video each time, including the key frames information which has a small cost, but might still have an impact in the end.
- `video_reader.get_batch()` is single threaded at the moment, because it was easier to implement and the performance difference on my use case was almost negligible: getting a small sub-clip of the video, like 32 or 64 frames, with resolution of 256 to 512. So it is still nice that it is *only* 2x slower than decord on a big video, while decord is multi-threaded AFAIK.

I could try to solve the first point by creating a VideoReader python class similar to the decord one. Regarding the second point it will probably take more time.

**Comment by NevermindNilas** [comment]
Hi, don't sweat it, first achieve the goal that you've envisioned and then maybe consider the edge cases like mine.

I am developing a little 'infrastructure/arch' for super fast ML / AI Related workloads such as upscaling, interpolation, depth map extraction.

https://github.com/NevermindNilas/TheAnimeScripter/

Currently it has gotten a false DMCA report from someone so sadly the repository is down for the time being but to elaborate the only real 2 tasks that reach such insane numbers are Interpolation with Rife ( specifically TensorRT ) and a couple of algorithms such as SSIM-CUDA / MSE that can get to these numbers. 

Here's a benchmark a friend of mine ran with a 7950x/4090
![image](https://github.com/gcanat/video_reader-rs/assets/128264457/80d9615e-574d-4fa7-8fd6-2bdb5468a2d3)


Honestly decode is still fast enough to not be a real bottleneck but as time goes on and I fix a couple of things I will get near decode / encode limits ( I already am heavily limited by encode speeds honestly ).

But to put it simply, if it can get faster, why not?

**Comment by NevermindNilas** [comment]
![image](https://github.com/gcanat/video_reader-rs/assets/128264457/78188269-4d5a-4c3d-85e6-3921d320e850)
Deduplication using MSE and no encode + FFMPEG Subprocess speed

![image](https://github.com/gcanat/video_reader-rs/assets/128264457/6bef7e4c-123d-49a7-ab79-c05c1cfdf5f7)
Just pure decode benchmarking ( deduplication logic is commented out since my script doesn't yet have a direct benchmark method for decode )

You can see why I am shooting for the stars 🤣

**Comment by gcanat** [comment]
I've made some changes to the `decode` method so you can specify a start_frame and end_frame to only decode frames between this range. This seems more appropriate then using the get_batch method which is more design to get random frames that can be spread across the video with no particular order.

So now you can try something like this:
```python
for i in tqdm(range(0, video_length, chunk_size)):
    end = min(i + chunk_size, video_length)
    frames = video_reader.decode(filename, start_frame=i, end_frame=end)
```
It will directly seek to start_frame and stop the decoding loop after end_frame is reached. In my experiment it is giving nice results. 

You can now directly install with `pip install video-reader-rs`
Let me know!

**Comment by NevermindNilas** [comment]
Hi,

I tested using this code
```py
import video_reader
from tqdm import tqdm
import cv2

videoname = "/home/nilas/Downloads/videoplayback.mp4"
chunk_size = 500

vr = int(cv2.VideoCapture(videoname).get(cv2.CAP_PROP_FRAME_COUNT))
print("Video length:", vr)

for i in tqdm(range(0, vr, chunk_size)):
    end = min(i + chunk_size, vr)
    frames = video_reader.decode(videoname, start_frame=i, end_frame=end)
```

Python 3.12 - Arch Linux - 13700k - 1920x1080p30fps
100%|█████████████████████████████████████████████████████████████████████████████████| 8/8 [00:11<00:00,  1.39s/it]

That's roughly 360fps, big improvements overall. Congrats!!

**Comment by NevermindNilas** [comment]
Quick update on my peak performance with Python 3.11 Arch Linux and 13700k,

I managed to decouple stdout.read chunk from the main loop and parallelize it to the best of my abilities.

```py
import numpy as np
import cv2
import subprocess
from tqdm import tqdm
import torch
import queue
import time
from concurrent.futures import ThreadPoolExecutor

videoPath = "/home/nilas/Downloads/videoplayback.mp4"
command = ["ffmpeg", '-i', videoPath, '-f', 'image2pipe', '-pix_fmt', 'rgb24', '-vcodec', 'rawvideo', '-']
chunk = 1920*1080*3

video = cv2.VideoCapture(videoPath)
frameCount = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
video.release()

frameQueue = queue.Queue(maxsize=500) # maxsize just to make sure it doesn't get too big

def read_frames():
    pipe = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    for _ in range(frameCount):
        raw_frame = pipe.stdout.read(chunk)
        frameQueue.put(raw_frame)

def process_frames():
    for _ in tqdm(range(frameCount)):
        try:
            if not frameQueue.empty():
                image = torch.frombuffer(frameQueue.get_nowait(), dtype=torch.uint8).reshape(1080, 1920, 3)
            else:
                time.sleep(0.01)
        except queue.Empty:
            time.sleep(0.01)

executor = ThreadPoolExecutor(max_workers=2)

reader_thread = executor.submit(read_frames)
processor_thread = executor.submit(process_frames)
```
```
100%|██████████████████████████████████████████████████████████████████████████| 3649/3649 [00:05<00:00, 727.76it/s]
```
With peaks of 760-770

Python 3.12 on Linux was peaking at around 720 but normalized at around 700+-
It's not perfect but it's a new baseline for me.

The same code on Windows with Python3.11 peaks at around 550-560
```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5727/5727 [00:11<00:00, 514.69it/s]
```

**Comment by gcanat** [comment]
Pushed some more improvements/fixes in the last release (v0.1.3). 

On my  weak laptop using a 3660x1080x1920 video, it takes 55sec with `video_reader` (chunksize=800) and 47sec with your `subprocess.Popen` method. The difference gets smaller with smaller resolutions.

I think at this point the bottleneck is inserting the frame array into the video array holding the chunk of frames. It is faster if i just push all frames into a vector and later stack the frames as a video array but the memory consumption is way higher this way.

**Comment by NevermindNilas** [comment]
Can you also test this?

```py
import numpy as np
import cv2
import subprocess
from tqdm import tqdm
import torch
import queue
import time
from concurrent.futures import ThreadPoolExecutor

videoPath = r"G:\TAS\input\input.mp4"
command = ["ffmpeg", '-i', videoPath, '-f', 'image2pipe', '-pix_fmt', 'yuv420p', '-vcodec', 'rawvideo', '-']

video = cv2.VideoCapture(videoPath)
frameCount = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
chunk = int(width * height * 1.5)
video.release()

frameQueue = queue.Queue(maxsize=500) # maxsize just to make sure it doesn't get too big

def yuv420p_to_rgb(raw_frame, width, height):
    yuv_frame = np.frombuffer(raw_frame, dtype=np.uint8).reshape((int(height * 1.5), width))
    rgb_frame = cv2.cvtColor(yuv_frame, cv2.COLOR_YUV2RGB_I420)
    return rgb_frame

def read_frames():
    pipe = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    for _ in range(frameCount):
        raw_frame = pipe.stdout.read(chunk)
        frameQueue.put(raw_frame)

def process_frames():
    for _ in tqdm(range(frameCount)):
        try:
            if not frameQueue.empty():
                rgb_frame = torch.from_numpy(yuv420p_to_rgb(frameQueue.get, width, height))
            else:
                time.sleep(0.001)
        except queue.Empty:
            time.sleep(0.001)

executor = ThreadPoolExecutor(max_workers=2)

reader_thread = executor.submit(read_frames)
processor_thread = executor.submit(process_frames)
```

My results on Windows at least have now doubled and are nearing the 900 FPS mark.
```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1651/1651 [00:01<00:00, 887.55it/s]
```

**Comment by NevermindNilas** [comment]
Oh actually if I increase the time sleep to 0.0001

I get upwards of 2000?
```
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1651/1651 [00:00<00:00, 1991.78it/s]```

There must be something wrong here

**Comment by gcanat** [comment]
Weird, this code snippet is not working on my side. Progress bar is stuck at 3%.

**Comment by NevermindNilas** [comment]
```py
import numpy as np
import cv2
import subprocess
from tqdm import tqdm
import torch
import queue
import time
from concurrent.futures import ThreadPoolExecutor

videoPath = r"G:\TAS\input\input.mp4"
ffmpegPath = r"G:\TAS\src\ffmpeg\ffmpeg.exe"
command = [ffmpegPath, '-i', videoPath, '-f', 'image2pipe', '-pix_fmt', 'yuv420p', '-vcodec', 'rawvideo', '-']

video = cv2.VideoCapture(videoPath)
frameCount = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
chunk = int(width * height * 1.5)
video.release()

frameQueue = queue.Queue(maxsize=500) # maxsize just to make sure it doesn't get too big

def yuv420p_to_bgr(raw_frame, width, height):
    # Reshape the raw frame to include Y, U, and V components
    yuv_frame = np.frombuffer(raw_frame, dtype=np.uint8).reshape((height + height // 2, width))
    # Convert YUV frame to BGR format
    bgr_frame = cv2.cvtColor(yuv_frame, cv2.COLOR_YUV2RGB_I420)
    return bgr_frame

def read_frames():
    pipe = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    for _ in range(frameCount):
        raw_frame = pipe.stdout.read(chunk)
        frameQueue.put(raw_frame)
    pipe.kill()

def process_frames():
    pBar= tqdm(total=frameCount)
    while True:
        try:
            if not frameQueue.empty():
                bgr_frame = yuv420p_to_bgr(frameQueue.get_nowait(), width, height)
                #cv2.imwrite(f"output/frame{i}.jpg", bgr_frame) # uncomment this line to save frames
                pBar.update(1)
            else:
                # try again
                time.sleep(0.00001)
        except Exception as e:
            print(e)

executor = ThreadPoolExecutor(max_workers=2)

reader_thread = executor.submit(read_frames)
processor_thread = executor.submit(process_frames)
```

Chunk size of 1.5 is needed because U and V from YUV is only half of the dimension of RGB so it's 
( Y 1920x1080 U 960x540 V 960x540 ). 

I Converted to BGR here instead of RGB and opencv seems to save it just fine without any issues, the threads aren't properly closing at times but it is nothing that can't be fixed.

The reason why I was getting such high FPS is that despite the fact that the for loop for process_frame was non blocking to the point that if the queue was empty, it would skip over and go try to fetch the next frame, with a while loop that gets fixed and the FPS becomes more reasonable in the neighborhood of 550-570. Slighly better but nothing to write home about.

**Comment by gcanat** [comment]
Ah yes it works now. It is fast indeed :+1: 

With this small modification to exit the loop.

```diff
def process_frames():
    pBar= tqdm(total=frameCount)
+   i = 0
    while True:
        try:
            if not frameQueue.empty():
                bgr_frame = yuv420p_to_bgr(frameQueue.get_nowait(), width, height)
                #cv2.imwrite(f"output/frame{i}.jpg", bgr_frame) # uncomment this line to save frames
                pBar.update(1)
+               i += 1
            else:
                # try again
                time.sleep(0.00001)
        except Exception as e:
            print(e)
+       if i == frameCount:
+           break
```
